version: '3'

services:

    nginx:
        image: nginx
        container_name: node-nginx
        ports:
            - 8080:80
        volumes:
            - ../app/vue:/var/www/
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    web:
        container_name: node
        build: .
        volumes:
            - ../app/vue:/var/www/
        stdin_open: true
        tty: true
        command: [sh, -c, npm run dev]
