version: '3'

services:

    node:
        container_name: node
        build: .
        ports:
            - 8080:8080
        volumes:
            - ../app/vue:/var/www/
        stdin_open: true
        tty: true
        command: [sh, -c, npm install && npm run dev]
